package com.kfood.shared.exceptions;

public enum ErrorCode {
  VALIDATION_ERROR,
  RESOURCE_NOT_FOUND,
  UNEXPECTED_ERROR,
  AUTH_INVALID_CREDENTIALS,
  AUTH_TOKEN_EXPIRED,
  AUTH_FORBIDDEN_ROLE,
  TENANT_ACCESS_DENIED,
  STORE_NOT_ACTIVE,
  STORE_OUTSIDE_BUSINESS_HOURS,
  DELIVERY_ZONE_NOT_SUPPORTED,
  MIN_ORDER_NOT_REACHED,
  CATALOG_ITEM_UNAVAILABLE,
  ORDER_STATUS_TRANSITION_INVALID,
  PAYMENT_PROVIDER_NOT_SUPPORTED,
  PAYMENT_PROVIDER_INVALID_RESPONSE,
  PAYMENT_PROVIDER_UNAVAILABLE,
  PAYMENT_PROVIDER_TIMEOUT,
  WEBHOOK_SIGNATURE_INVALID,
  IDEMPOTENCY_KEY_REUSED_WITH_DIFFERENT_PAYLOAD
}
