spring:
  datasource:
    url: ${DB_URL:jdbc:postgresql://localhost:5432/kfood}
    username: ${DB_USERNAME:kfood}
    password: ${DB_PASSWORD:kfood}
    driver-class-name: org.postgresql.Driver

  data:
    redis:
      host: ${REDIS_HOST:localhost}
      port: ${REDIS_PORT:6379}

  rabbitmq:
    host: ${RABBITMQ_HOST:localhost}
    port: ${RABBITMQ_PORT:5672}
    username: ${RABBITMQ_USERNAME:kfood}
    password: ${RABBITMQ_PASSWORD:kfood}

app:
  eventing:
    rabbit:
      enabled: true
      startup-verify: true
      exchange: kfood.events
      order-created:
        queue: kfood.order.created.q
        routing-key: order.created
      order-status-changed:
        queue: kfood.order.status.changed.q
        routing-key: order.status.changed
      payment-confirmed:
        queue: kfood.payment.confirmed.q
        routing-key: payment.confirmed
  security:
    jwt-secret: ${JWT_SECRET:local-dev-secret-change-me-12345}
    jwt-expiration-seconds: ${JWT_EXPIRATION_SECONDS:3600}

management:
  endpoint:
    health:
      group:
        readiness:
          include: readinessState,db,redis,rabbit,ping
        liveness:
          include: livenessState,ping
      show-details: when_authorized
      show-components: when_authorized
